project:
  type: website

website:
  title: "Gakyeong Bae"
  back-to-top-navigation: true
  page-footer: 
    left: "Copyright 2025, Gakyeong Bae" 
    foreground: light
  navbar:
    foreground: light
    pinned: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Visualization"
        href: data_visualization/data_visualization.qmd
      - text: "Database"
        href: database/database.qmd
      - text: "Machine_learning"
        href: machine_learning/machine_learning.qmd
      - text: "Analysis"
        href: data_analysis/data_analysis.qmd
      - text: "Survey"
        href: quality_analysis/survey.qmd
      
      

language: 
  search-text-placeholder: "Search"
  show-itm-context: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    js: scripts.js
    toc: true

